#!/usr/bin/env python3

import sys

import grpc

import app_pb2
import app_pb2_grpc

def main():
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = app_pb2_grpc.DataServiceStub(channel)
        for line in sys.stdin:
            response = stub.GetData(app_pb2.DataRequest(name=line))
            print("Received: " + str(response.number) + ", " + response.label)

if __name__ == '__main__':
    main()
